spring:
  application:
    name: spring-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/goals
    username: goals_user
    password: supersecret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
